### PR TITLE
Remove `z-register` requirement for the save position option

### PR DESCRIPTION
**Pull request by thalesmello**
This pull request also changes the default value of the setting,
so that it saves position by default.

My motivation with this was mainly to get rid of the multichange
configuration in my vimrc, which is just one line.

If you think it's not desireable to change the default value of
the option, I can change this pull request.

### CODE REVIEW

**Comment by thalesmello** [comment]
By the way, I also removed the mark from the entire buffer command. I've noticed it was not necessary.

**Comment by AndrewRadev** [comment]
This seems reasonable, and I have no problem with making the position-saving a default. I'm not even sure if there needs to be an option if it doesn't clobber the `z` mark, but it's there, so why not :).

Could you rename the variable, though, maybe something like `g:multichange_memo_position` with a small `m`? I would also appreciate if you tried to make it a script-local variable, because it's all in one script anyway. It would be set with `let s:multichange_memo_position = ...`, and it would be used in the mapping with `<SID>multichange_memo_position` (The same way the `s:MultichangeMotion` function is called). I'm not 100% sure it'll work, but if you try it out, I'd appreciate it -- one less global variable :).

**Comment by thalesmello** [comment]
@AndrewRadev I had to create an extra function, otherwise I wan't able to set a script variable directly from the mapping. Either way, I also simplified the code.

It always saves the position before the operation, regardless of the setting.
If the setting is disable, it simply doesn't move.

It removes the if clause from the mapping, making the code simpler.

**Comment by AndrewRadev** [comment]
I merged the PR, and I added one more commit on top with some minor changes: https://github.com/AndrewRadev/multichange.vim/commit/2dfd35d1c329528953ea2be7c9fcb35184ec6ecb

Thanks for your work :).

**Pull request merged**
